steps:
  - command: echo "Checks out multiple git repositories"
    plugins:
      - hasura/smooth-checkout#v4.1.1:
          build_checkout_path: "dynamic-pipeline"
          repos:
            - config:
              - url: https://github.com/hnadimint/Dynamic_go-pipeline.git   
    #command: "cd dy-go-pipeline && go run main.go | buildkite-agent pipeline upload"
    command: "ls -lR && ls -lR ../"
